{{- if eq .Values.inventory.discovery.scope "Cluster" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-inventory" .Release.Name }}
rules:
- apiGroups: ["virtualization.deckhouse.io"]
  resources: ["virtualmachines"]
  verbs: ["get", "list", "watch"]
{{- end }}
