{{- if not (hasKey .Values.inventory "discovery") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-inventory-secrets" .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: [{{ printf "%s-inventory-config" .Release.Name | quote }}]
  verbs: ["get", "update", "patch", "delete"]
- apiGroups: ["awx.ansible.com"]
  resources: ["awxs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["virtualization.deckhouse.io"]
  resources: ["virtualmachines"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-inventory-secrets" .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-inventory-secrets" .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ printf "%s-inventory" .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- else if eq .Values.inventory.discovery.scope "Cluster" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-inventory-secrets" .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: [{{ printf "%s-inventory-config" .Release.Name | quote }}]
  verbs: ["get", "update", "patch", "delete"]
- apiGroups: ["awx.ansible.com"]
  resources: ["awxs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-inventory-secrets" .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-inventory-secrets" .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ printf "%s-inventory" .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- else if and (eq .Values.inventory.discovery.scope "Custom") .Values.inventory.discovery.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-inventory-vms" .Release.Name }}
rules:
- apiGroups: ["virtualization.deckhouse.io"]
  resources: ["virtualmachines"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-inventory-vms" .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-inventory-vms" .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ printf "%s-inventory" .Release.Name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-inventory-secrets" .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: [{{ printf "%s-inventory-config" .Release.Name | quote }}]
  verbs: ["get", "update", "patch", "delete"]
- apiGroups: ["awx.ansible.com"]
  resources: ["awxs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-inventory-secrets" .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-inventory-secrets" .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ printf "%s-inventory" .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
