---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awx-operator-manager-cluster-role
rules:
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs: &all-verbs
      - get
      - list
      - create
      - delete
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - services/finalizers
      - serviceaccounts
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs: *all-verbs
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs: *all-verbs
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs: *all-verbs
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: *all-verbs
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - create
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - apps
    resources:
      - deployments/scale
      - statefulsets/scale
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/exec
      - pods/attach
      - pods/log
    verbs:
      - create
      - get
  - apiGroups:
      - awx.ansible.com
    resources:
      - "*"
      - awxbackups
      - awxrestores
    verbs:
      - "*"
  - apiGroups:
      - traefik.containo.us
      - traefik.io
    resources:
      - ingressroutetcps
    verbs: *all-verbs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: awx-operator-manager-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awx-operator-manager-cluster-role
subjects:
  - kind: ServiceAccount
    name: awx-operator-controller-manager
    namespace: awx
