apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualMachine
metadata:
  name: demo-vm
  labels:
    vm: demo-vm
  annotations:
    provisioning.virtualization.deckhouse.io/groups: "test,demo"
    provisioning.virtualization.deckhouse.io/ansible_user: "cloud"
spec:
  virtualMachineClassName: generic
  runPolicy: AlwaysOn
  cpu:
    cores: 1
    coreFraction: 50%
  disruptions:
    restartApprovalMode: Automatic
  memory:
    size: 2Gi
  provisioning:
    type: UserDataRef
    userDataRef:
      kind: Secret
      name: cloud-init-demo-vm
  blockDeviceRefs:
    - kind: VirtualDisk
      name: root-disk-demo-vm
