---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  admin_user: admin
  admin_password_secret: awx-admin-password

  # service_type: nodeport
  # nodeport_port: 31768

  ingress_type: ingress
  ingress_hosts:
    - hostname: awx.example.com
      tls_secret: awx-secret-tls

  postgres_configuration_secret: awx-postgres-configuration

  # postgres_data_volume_init: true
  # postgres_storage_class: rv-thin-r1
  # postgres_storage_requirements:
  #   requests:
  #     storage: 8Gi

  projects_persistence: true
  projects_existing_claim: awx-projects-claim

  web_replicas: 1
  # task_replicas: 2

  web_resource_requirements: {}
  task_resource_requirements: {}
  ee_resource_requirements: {}
  init_container_resource_requirements: {}
  postgres_resource_requirements: {}
  redis_resource_requirements: {}
  rsyslog_resource_requirements: {}

  task_manage_replicas: true

  # /api/v2/metrics/
  # metrics_utility_enabled: true

  # extra_settings:
  #   - setting: ALLOW_METRICS_FOR_ANONYMOUS_USERS
  #     value: "True"

  # ingress_annotations: |
  #   nginx.ingress.kubernetes.io/configuration-snippet: |
  #     if ($request_uri = "/api/v2/metrics") {
  #       deny all;
  #       return 403;
  #     }
  # web_extra_volume_mounts: |
  #   - name: awx-static-data
  #     mountPath: /var/lib/awx/projects
  # extra_volumes: |
  #   - name: awx-static-data
  #     persistentVolumeClaim:
  #       claimName: awx-static-data
  # # Добавить init контейнер для инициализации
  # extra_init_containers: |
  #   - name: init-projects
  #     image: busybox:latest
  #     command:
  #       - sh
  #       - -c
  #       - |
  #         mkdir -p /data/demo-playbooks
  #         mkdir -p /data/demo-roles/webserver/tasks
  #         echo "---
  #         - name: Demo
  #           hosts: localhost
  #           tasks:
  #             - debug: msg='Hello'" > /data/demo-playbooks/hello.yml
  #         chmod -R 755 /data
  #     volumeMounts:
  #       - name: awx-static-data
  #         mountPath: /data
