---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: awx
  namespace: awx
spec:
  certificateOwnerRef: false
  dnsNames:
    - awx.example.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: awx-secret-tls
