---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-static-data
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
