---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-admin-password" .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.awx.admin.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-postgres-configuration" .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  host: {{ printf "d8ms-pg-%s-rw.%s.svc" .Release.Name .Release.Namespace | quote }}
  port: "5432"
  database: {{ .Values.db.database | default "awx" | quote }}
  username: {{ .Values.db.user | default "awx" | quote }}
  password: {{ .Values.db.password | quote }}
  sslmode: {{ .Values.db.sslmode | default "disable" | quote }}
